services:
  - type: web
    name: cc-checker-site
    env: python
    plan: free
    buildCommand: ""
    startCommand: "gunicorn app:app --bind 0.0.0.0:5000"
    envVars:
      - key: PORT
        value: "5000"
